### ISSUE TITLE
Game doesn't work on iOS 9.3.2 (It's deployment target)

### ISSUE THREAD

**Issue by fluidityt** [prolific8/fruit-dodge#2]
I've tried the game on my actual 5c and on the 4s simulator, both are 9.3.2, and the monkey will only turn  left / right without moving, and none of the collisions work.  The game works fine on the 10+ simulators.

**Comment by fluidityt** [comment]
if you have any ideas on what may cause this issue let me know. I know that there are a few things in my own codebase that for random reasons don't work on 9.3 that I have made workarounds for. I didn't see anything obvious in yours that would warrant it not working. It seems like it may be related to the state machine, but its VERY strange that the character will change directions, but not move, AND that none of the collisions work.

**Comment by prolific8** [comment]
I've run on the 9.3 simulator and confirmed this is occurring on my copy as well.

The state changes appear to be happening as the animation textures are run and these are part of the state classes. I think the problem is with the physics bodies of the character and the enemies.

**Comment by prolific8** [comment]
Physics body for the player was being created twice. iOS9 didn't like the second creation and would fail.
